spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/botdb
    username: postgres
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
